Resistor = 4.7

[User]
  BetaId = ""
  Name = ""

[Battery]
  BetaRef = ""
  Type = ""
  Voltage = 0
  Brand = ""
  Model = ""

[Regenbox]
  Mode = "Charger"
  NbHalfCycles = 10
  UpDuration = "24h0m0s"
  DownDuration = "24h0m0s"
  TopVoltage = 1500
  BottomVoltage = 900
  Ticker = "60s"
  ChargeFirst = false
  Battery1 = true
  Battery2 = true
  Battery3 = true
  Battery4 = true

[Web]
  ListenAddr = "localhost:3636"
  StaticDir = "static"
  DataDir = "data"
  WebsocketInterval = "5s"

[Watcher]
  ConnPollRate = "1s"

[Serial]
  BaudRate = 57600
  DataBits = 8
  Parity = 0
  StopBits = 0
