// Code generated by "stringer -type=Mode"; DO NOT EDIT.

package regenbox

import "fmt"

const _Mode_name = "ManualDischargeOnlyChargeOnlyAutoRun"

var _Mode_index = [...]uint8{0, 6, 19, 29, 36}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return fmt.Sprintf("Mode(%d)", i)
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
